# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: xiaoaiwhc's blog
email: xiaoaiwhc@qq.com
description: > # this means to ignore newlines until "baseurl:"
  xiaoaiwhc's blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xiaoai.github.io" # the base hostname & protocol for your site
twitter_username: xiaoaiwhc
github_username:  xiaoaiwhc

# Build settings
markdown: kramdown
